site_name: 'Boardies Docs'
site_description: 'Boardies Docs'
site_author: 'Nindi Gill'
site_url: 'https://docs.boardies.software'
copyright: 'Copyright &copy; 2020 Boardies Software'
dev_addr: '0.0.0.0:8000'

theme:
  name: 'material'
  favicon: 'images/favicon.png'
  features:
    - tabs
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'en'
  logo: 'images/boardies.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'

extra:
  social:
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/boardiesoftware'
    - icon: 'fontawesome/brands/slack'
      link: 'https://macadmins.slack.com/archives/G015C05692M'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: 'date'

nav:
  - Home: 'index.md'
  - User Guide:
    - Welcome: 'user-guide/welcome.md'
  - Release Notes:
    - What's New: 'release-notes/whats-new.md'
    - Known Issues: 'release-notes/known-issues.md'
